import { Inter } from "next/font/google";
import "react-loading-skeleton/dist/skeleton.css";
import Navbar from "../components/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tailwindcss, typescript, and Next.js 13 basic components",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        {children}
        <Navbar />
      </body>
    </html>
  );
}
